version: '3'
services:
  listener:
    image: "saltstack/salt:2019.2.0"
    ports:
    - "4505:4505"
    - "4506:4506"
    - "9000:9000"
    volumes:
     - ./config:/etc/salt/master.d
     - ./salt:/srv/salt

